import { calculateCorporationTax } from './corporation-tax';
import { calculateDividendTax } from './dividend-tax';
import { calculateIncomeTax } from './income-tax';
import { calculateNic } from './nic';
import { calculateStudentLoan } from './student-loan';
import { CalculationInput, TaxBreakdown } from './types';

export function calculateTakeHome(input: CalculationInput): TaxBreakdown {
    // 1. National Insurance (first because Employer NIC reduces Corp Tax)
    const nicResult = calculateNic(input);

    // 2. Corporation Tax
    const ctResult = calculateCorporationTax(input, nicResult.employer);

    // 3. Income Tax (Salary)
    // Taxable Salary = Salary - PA (Tapered)
    // We need to run income tax logic to get the taxable amount used.
    const incomeTaxResult = calculateIncomeTax(input, input.annualSalary + input.otherTaxableIncome);
    // Note: 'otherTaxableIncome' is lumped with salary for Income Tax band consumption (Non-Savings Income)

    // 4. Dividend Tax
    // Dividends sit on top of (Salary + Other).
    // We need the *Taxable* income from step 3 to know where dividends start in the bands.
    // Actually, bands apply to "Total Income" usually?
    // No, bands apply to Net Taxable Income.
    // Adjusted PA is deducted first.
    // Net Taxable Salary = (Salary + Other) - AdjustedPA.
    // This is the starting point for Dividends in the bands.

    // Calculate Net Taxable Non-Savings Income
    const netTaxableNonSavings = Math.max(0, (input.annualSalary + input.otherTaxableIncome) - incomeTaxResult.adjustedPersonalAllowance);

    const dividendTax = calculateDividendTax(input, netTaxableNonSavings, input.annualDividends);

    // 5. Student Loan
    // Based on total income (Salary + Dividends + Other)
    const totalStudentLoanIncome = input.annualSalary + input.annualDividends + input.otherTaxableIncome;
    const studentLoan = calculateStudentLoan(totalStudentLoanIncome, input.studentLoanPlan);

    // 6. Aggregation
    const totalTax = incomeTaxResult.tax + nicResult.employee + dividendTax + studentLoan;
    const totalPersonalTax = totalTax;

    const grossIncome = input.annualSalary + input.annualDividends + input.otherTaxableIncome;
    const takeHome = grossIncome - totalPersonalTax;

    const totalCompanyTax = ctResult.corporationTax + nicResult.employer;

    return {
        inputs: input,
        results: {
            grossIncome,
            taxableIncome: netTaxableNonSavings + input.annualDividends, // Approx
            totalTax: totalPersonalTax,
            takeHome,
            effectiveTaxRate: totalPersonalTax / grossIncome,
            marginalRate: 0, // Todo: calculate marginal logic if needed
            distributableProfitAfterCT: ctResult.distributableProfit
        },
        deductions: {
            incomeTax: incomeTaxResult.tax,
            nicEmployee: nicResult.employee,
            nicEmployer: nicResult.employer,
            corporationTax: ctResult.corporationTax,
            dividendTax: dividendTax,
            studentLoan,
            totalPersonalTax,
            totalCompanyTax,
            totalTaxAndNic: totalPersonalTax + totalCompanyTax // Total tax burden generated by this director's remuneration
        }
    };
}
